# Generated by Django 4.2 on 2024-06-04 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_direccion', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=10)),
                ('depto', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_inmueble',
            fields=[
                ('id_tipo_inmueble', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.TextField(choices=[('Departamento', 'Departamento'), ('Casa', 'Casa'), ('Parcela', 'Parcela')])),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_usuario',
            fields=[
                ('id_tipo_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Arrendador', 'Arrendador'), ('Arrendatario', 'Arrendatario')])),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_region', models.CharField(max_length=50)),
                ('nombre_ciudad', models.CharField(max_length=50)),
                ('nombre_comuna', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254)),
                ('id_direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_arriendos.direccion')),
                ('tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_arriendos.tipo_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Inmuebles',
            fields=[
                ('id_inmueble', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('m2_construidos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('m2_terreno', models.DecimalField(decimal_places=2, max_digits=10)),
                ('n_estacionamientos', models.IntegerField()),
                ('n_banos', models.IntegerField()),
                ('n_habitaciones', models.IntegerField()),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Arrendado', 'Arrendado')])),
                ('id_direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_arriendos.direccion')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_arriendos.usuarios')),
                ('tipo_inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_arriendos.tipo_inmueble')),
            ],
        ),
        migrations.AddField(
            model_name='direccion',
            name='id_ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_arriendos.ubicacion'),
        ),
    ]
