# Generated by Django 4.2 on 2024-06-05 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_arriendos', '0002_remove_ubicacion_nombre_ciudad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmuebles',
            name='m2_construidos',
        ),
        migrations.RemoveField(
            model_name='inmuebles',
            name='m2_terreno',
        ),
        migrations.RemoveField(
            model_name='inmuebles',
            name='precio_mensual',
        ),
    ]
