# Generated by Django 4.2 on 2024-06-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_arriendos', '0003_remove_inmuebles_m2_construidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmuebles',
            name='m2_construidos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='m2_terreno',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='precio_mensual',
            field=models.IntegerField(default=0),
        ),
    ]
